addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"   % "0.6.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.3.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.10.1")
addSbtPlugin("com.lightbend.akka.grpc"   % "sbt-akka-grpc" % "2.1.4")
addSbtPlugin("io.gatling"                % "gatling-sbt"   % "4.2.1")
